<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'footer_contact' => 'Contáctanos',
    'footer_description' => 'Aquí va la descripción en español',
    'footer_links' => 'Enlaces',
    'footer_more_links' => 'Más enlaces',
    'footer_title' => 'Título de la página',
    'header_about' => 'Acerca de',
    'header_home' => 'Inicio',
    'header_login' => 'Inicia Sesión',
    'header_sign_up' => 'Regístrate',
    'index_contact_title' => 'Contacto',
    'index_login_title' => 'Inicia Sesión',
    'index_title' => 'Inicio',
    'reset_message' => 'Si olvidaste o perdiste tu contraseña',
    'reset_password_link' => 'reiníciala',
];
